export const slepicky = [
  {
    href: '/eshop/slepicky/D853',
    label: 'Kuřice Dominant Červený D853',
    src: '/slepicky/D853.png',
    price: 280,
  },
  {
    href: '/eshop/slepicky/D159',
    label: 'Kuřice Dominant Červeně Žíhaný D159',
    src: '/slepicky/D159.png',
    price: 280,
  },
  {
    href: '/eshop/slepicky/D109',
    label: 'Kuřice Dominant Černý D109',
    src: '/slepicky/D109.png',
    price: 280,
  },
  {
    href: '/eshop/slepicky/D959',
    label: 'Kuřice Dominant Žíhaný D959',
    src: '/slepicky/D959.png',
    price: 280,
  },
  {
    href: '/eshop/slepicky/D104',
    label: 'Kuřice Dominant Sussex D104',
    src: '/slepicky/D104.png',
    price: 280,
  },
  {
    href: '/eshop/slepicky/D107',
    label: 'Kuřice Dominant Modrý D107',
    src: '/slepicky/D107.png',
    price: 280,
  },
  {
    href: '/eshop/slepicky/D229',
    label: 'Kuřice Dominant Leghorn D229',
    src: '/slepicky/D229.png',
    price: 280,
  },
  {
    href: '/eshop/slepicky/D300',
    label: 'Kuřice Dominant Vlaška koroptví D300',
    src: '/slepicky/D300.png',
    price: 280,
  },
  {
    href: '/eshop/slepicky/GS',
    label: 'Kuřice Dominant Greenshell',
    src: '/slepicky/GS.png',
    price: 300,
  },
  {
    href: '/eshop/slepicky/DS',
    label: 'Kuřice Dominant Darkshell',
    src: '/slepicky/DS.png',
    price: 300,
  },
  {
    href: '/eshop/slepicky/kohout',
    label: 'Kohout',
    src: '/slepicky/kohout/1.png',
    price: 300,
  },
]

export const kurniky = [
  {
    href: '/eshop/kurniky/kurnik-10-tepleny',
    label: 'Kurník na 10 slepic teplený',
    src: '/kurniky/kurnik-10-tepleny/1.jpg',
    price: 39930,
  },
  {
    href: '/eshop/kurniky/kurnik-20-tepleny/',
    label: 'Kurník na 20 slepic teplený',
    src: '/kurniky/kurnik-20-tepleny/1.jpg',
    price: 45980,
  },
  {
    href: '/eshop/kurniky/kurnik-6-netepleny/',
    label: 'Kurník na 6 slepic neteplený',
    src: '/kurniky/kurnik-6-netepleny/1.jpg',
    price: 9500,
  },
  {
    href: '/eshop/kurniky/kurnik-10-netepleny',
    label: 'Kurník na 10 slepic neteplený',
    src: '/kurniky/kurnik-10-netepleny/1.jpg',
    price: 24200,
  },
  {
    href: '/eshop/kurniky/kurnik-20-netepleny',
    label: 'Kurník na 20 slepic neteplený',
    src: '/kurniky/kurnik-20-netepleny/1.jpg',
    price: 27830,
  },
  {
    href: '/eshop/kurniky/kurnik-terasovy',
    label: 'Kurník terasový / balkonový s trusníkem',
    src: '/kurniky/kurnik-terasovy/1.jpg',
    price: 15125,
  },
  {
    href: '/eshop/kurniky/vybeh-bez-vstupu',
    label: 'Uzavřený výběh bez vstupu 1/2 krytý',
    src: '/kurniky/vybeh-bez-vstupu/1.jpg',
    price: 7865,
  },
  {
    href: '/eshop/kurniky/vybeh-se-vstupem',
    label: 'Uzavřený výběh se vstupem',
    src: '/kurniky/vybeh-se-vstupem/1.jpg',
    price: 15125,
  },
  {
    href: '/eshop/kurniky/kralikarna-6',
    label: 'Králíkárna 6 kotcová',
    src: '/kurniky/kralikarna-6/1.jpg',
    price: 30250,
  },
  {
    href: '/eshop/kurniky/kralikarna-4',
    label: 'Králíkárna 4 kotcová',
    src: '/kurniky/kralikarna-4/1.jpg',
    price: 22990,
  },
  {
    href: '/eshop/kurniky/bedna-preprava',
    label: 'Bedna na přepravu slepic',
    src: '/kurniky/bedna-preprava/1.jpg',
    price: 800,
  },
  {
    href: '/eshop/kurniky/vybeh',
    label: 'Výběh',
    src: '/kurniky/vybeh/1.jpg',
    price: 10890,
  },
]

export const smesi = [
  {
    href: '/eshop/smesi/startovaci-balicek',
    label: 'Startovací balíček',
    src: '/smesi/startovaci-balicek/1.jpg',
    price: 600,
  },
  {
    href: '/eshop/smesi/krouzky',
    label: 'Kroužky',
    src: '/smesi/krouzky.jpg',
    price: 8,
  },
  {
    href: '/eshop/smesi/ochrana-proti-cmelikum-acaritec',
    label: 'Ochrana proti čmelíkum - Acaritec (bio)',
    src: '/smesi/ochrana-proti-cmelikum.jpg',
    price: 400,
  },
  {
    href: '/eshop/smesi/ochrana-proti-cmelikum-acariflash',
    label: 'Ochrana proti čmelíkum - Acariflash (bio)',
    src: '/smesi/ochrana-proti-cmelikum.jpg',
    price: 400,
  },
  {
    href: '/eshop/smesi/ochrana-proti-cmelikum-mistral-layer',
    label: 'Ochrana proti čmelíkum - Mistral Layer (bio)',
    src: '/smesi/ochrana-proti-cmelikum.jpg',
    price: 400,
  },
  {
    href: '/eshop/smesi/alize',
    label: 'Alizé',
    src: '/smesi/alize.jpg',
    price: 300,
  },
  {
    href: '/eshop/smesi/galli-sweet',
    label: 'Galli sweet',
    src: '/smesi/galli-sweet.jpg',
    price: 380,
  },
  {
    href: '/eshop/smesi/calciplus-250ml',
    label: 'Calciplus 250ml',
    src: '/smesi/calciplus-250ml.jpg',
    price: 200,
  },
  {
    href: '/eshop/smesi/supervitd',
    label: 'Supervit D',
    src: '/smesi/supervitd.jpg',
    price: 40,
  },
  {
    href: '/eshop/smesi/c-compositum-50-500g',
    label: 'C-compositum 50 500g',
    src: '/smesi/c-compositum-50-500g.jpg',
    price: 300,
  },
  {
    href: '/eshop/smesi/aminosol-1l',
    label: 'Aminosol 1L',
    src: '/smesi/aminosol-1l.jpg',
    price: 400,
  },
  {
    href: '/eshop/smesi/aminosol-250ml',
    label: 'Aminosol 250ml',
    src: '/smesi/aminosol-250ml.jpg',
    price: 200,
  },
  {
    href: '/eshop/smesi/kombisol-ad3-30ml',
    label: 'Kombisol AD3 30ml',
    src: '/smesi/kombisol-ad3-30ml.jpg',
    price: 90,
  },
  {
    href: '/eshop/smesi/kombisol-ad3e-1l',
    label: 'Kombisol AD3E 1L',
    src: '/smesi/kombisol-ad3e-1l.jpg',
    price: 950,
  },
  {
    href: '/eshop/smesi/kombisol-ad3e-250ml',
    label: 'Kombisol AD3E 250ml',
    src: '/smesi/kombisol-ad3e-250ml.jpg',
    price: 300,
  },
  {
    href: '/eshop/smesi/kombisol-ad3e-30ml',
    label: 'Kombisol AD3E 30ml',
    src: '/smesi/kombisol-ad3e-30ml.jpg',
    price: 90,
  },
  {
    href: '/eshop/smesi/nutrimix-forticoat-1l',
    label: 'Nutrimix forticoat 1L',
    src: '/smesi/nutrimix-forticoat-1l.jpg',
    price: 300,
  },
  {
    href: '/eshop/smesi/nutrimix-forticoat-250ml',
    label: 'Nutrimix forticoat 250ml',
    src: '/smesi/nutrimix-forticoat-250ml.jpg',
    price: 120,
  },
  {
    href: '/eshop/smesi/nutrimix-3kg-odchov',
    label: 'Nutrimix 3kg odchov',
    src: '/smesi/nutrimix-3kg-odchov.jpg',
    price: 220,
  },
  {
    href: '/eshop/smesi/nutrimix-1kg-odchov',
    label: 'Nutrimix 1kg odchov',
    src: '/smesi/nutrimix-1kg-odchov.jpg',
    price: 90,
  },
  {
    href: '/eshop/smesi/nutrimix-3kg-vykrm',
    label: 'Mutrimix 3kg výkrm',
    src: '/smesi/nutrimix-3kg-vykrm.jpg',
    price: 200,
  },
  {
    href: '/eshop/smesi/nutrimix-1kg-vykrm',
    label: 'Nutrimix 1kg výkrm',
    src: '/smesi/nutrimix-1kg-vykrm.jpg',
    price: 70,
  },
]

export const doplnky = [
  {
    href: '/eshop/doplnky/zasterka-velka',
    label: 'Zástěrka s kapsami na sběr vajec velká',
    src: '/doplnky/zasterka-velka.jpg',
    price: 425,
  },
  {
    href: '/eshop/doplnky/zasterka-mala',
    label: 'Zástěrka s kapsami na sběr vajec malá',
    src: '/doplnky/zasterka-mala.jpg',
    price: 300,
  },
  {
    href: '/eshop/doplnky/krmitko',
    label: 'Krmítko 30L',
    src: '/doplnky/krmitko.png',
    price: 1500,
    transparentBg: true,
  },
  {
    href: '/eshop/doplnky/pitko',
    label: 'Pítko 30L',
    src: '/doplnky/pitko.png',
    price: 1000,
    transparentBg: true,
  },
]
